version: '3'
networks:
  k6_network:
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - k6_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - k6_network

  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "5665:5665"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./docs/k6:/scripts
    depends_on:
      - influxdb
    command: [ "run", "/scripts/reservation_script.js" ]
    networks:
      - k6_network

volumes:
  influxdb-data:
  grafana-data:
